CREATE DATABASE OPTUS;
GO

USE OPTUS;
GO

CREATE TABLE ARTISTA(
idArtista TINYINT PRIMARY KEY IDENTITY(1,1),
nomeArtista VARCHAR(256) NOT NULL
);
GO

CREATE TABLE TIPOUSUARIO(
idTipoUsuario TINYINT PRIMARY KEY IDENTITY(1,1),
tipo VARCHAR(10) NOT NULL
);

CREATE TABLE ESTILO(
idEstilo SMALLINT PRIMARY KEY IDENTITY(1,1),
tipoEstilo VARCHAR(50) NOT NULL
);

CREATE TABLE USUARIO(
idUsuario INT PRIMARY KEY IDENTITY(1,1),
idTipoUsuario TINYINT FOREIGN KEY REFERENCES TIPOUSUARIO(idTipoUsuario),
email VARCHAR(256) NOT NULL,
nome VARCHAR(70) NOT NULL,
senha VARCHAR(12) NOT NULL
);

CREATE TABLE ALBUM(
idAlbum INT PRIMARY KEY IDENTITY(1,1),
idUsuario INT FOREIGN KEY REFERENCES USUARIO(idUsuario),
idEstilo SMALLINT FOREIGN KEY REFERENCES ESTILO(idEstilo),
artista VARCHAR(70) NOT NULL,
dataLancamento DATE NOT NULL
);

ALTER TABLE ALBUM 
DROP COLUMN artista;

ALTER TABLE ALBUM
ADD idArtista TINYINT FOREIGN KEY REFERENCES ARTISTA(idArtista);

ALTER TABLE ALBUM 
ADD nomeAlbum VARCHAR(100);

ALTER TABLE ALBUM 
ADD statusAlbum CHAR(1);