CREATE DATABASE OPTUS;
GO

USE OPTUS;
GO

CREATE TABLE TIPOUSUARIO(
idTipoUsuario TINYINT PRIMARY KEY IDENTITY(1,1),
tipo VARCHAR(10) NOT NULL
);

CREATE TABLE ESTILO(
idEstilo SMALLINT PRIMARY KEY IDENTITY(1,1),
tipoEstilo VARCHAR(50) NOT NULL
);

CREATE TABLE USUARIO(
idUsuario INT PRIMARY KEY IDENTITY(1,1),
idTipoUsuario TINYINT FOREIGN KEY REFERENCES TIPOUSUARIO(idTipoUsuario),
email VARCHAR(256) NOT NULL,
nome VARCHAR(70) NOT NULL,
senha VARCHAR(12) NOT NULL
);

CREATE TABLE ALBUM(
idAlbum INT PRIMARY KEY IDENTITY(1,1),
idUsuario INT FOREIGN KEY REFERENCES USUARIO(idUsuario),
idEstilo SMALLINT FOREIGN KEY REFERENCES ESTILO(idEstilo),
artista VARCHAR(70) NOT NULL,
dataLancamento DATE NOT NULL
);