CREATE DATABASE _PCLINICS;
GO

USE _PCLINICS;
GO

--DROP TABLE CLINICA
--DROP TABLE DONO
--DROP TABLE TIPOPET
--DROP TABLE RACA
--DROP TABLE VETERINARIO
--DROP TABLE PET
--DROP TABLE ATENDIMENTO

CREATE TABLE CLINICA(
idClinica TINYINT PRIMARY KEY IDENTITY(1,1),
nomeClinica VARCHAR(60) NOT NULL
);
GO

CREATE TABLE DONO(
idDono INT PRIMARY KEY IDENTITY(1,1),
nomeDono VARCHAR(60) NOT NULL
);
GO

CREATE TABLE TIPOPET(
idTipoPet INT PRIMARY KEY IDENTITY(1,1),
nomeEspecie VARCHAR(20) NOT NULL
);
GO

CREATE TABLE RACA(
idRaca INT PRIMARY KEY IDENTITY(1,1),
idTipoPet INT FOREIGN KEY REFERENCES TIPOPET(idTipoPet),
nomeRaca VARCHAR(50) NOT NULL
);
GO

CREATE TABLE VETERINARIO(
idVeterinario INT PRIMARY KEY IDENTITY(1,1),
idClinica TINYINT FOREIGN KEY REFERENCES CLINICA(idClinica),
nomeVeterinario VARCHAR(70) NOT NULL
);
GO


CREATE TABLE PET(
idPet INT PRIMARY KEY IDENTITY(1,1),
idRaca INT FOREIGN KEY REFERENCES RACA (idRaca),
idDono INT FOREIGN KEY REFERENCES DONO(idDono),
nomePet VARCHAR(50) NOT NULL
);
GO

CREATE TABLE ATENDIMENTO(
idAtendimento INT PRIMARY KEY IDENTITY(1,1),
idVeterinario INT FOREIGN KEY REFERENCES VETERINARIO(idVeterinario),
idPet INT FOREIGN KEY REFERENCES PET(idPet),
dataAtendimento DATE NOT NULL
);
GO

ALTER TABLE ATENDIMENTO
ADD descrAtendimento VARCHAR(256);

ALTER TABLE VETERINARIO
ADD CRMV INT;


ALTER TABLE CLINICA
ADD razaoSocial VARCHAR(256);
